In [1]:
import duckdb

In [3]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [4]:
df = con.execute(""" select * from produtos """).fetchdf()
df.head()

      ID NM_PRODUTO ID_CATEGORIA  ID_FORNECEDOR  VL_PRECO
0  10002    MARTELO         BT50            100    1500.0
1  10001   PARAFUSO         BT10            100     100.0
2  10004      SERRA         BT50            100     200.0
3  10003      PREGO         BT10            100      60.0

In [5]:
df2 = df.drop(columns=['ID_CATEGORIA', 'ID_FORNECEDOR'])

In [11]:
df2.head()
con.execute("""
drop table dim_produtos
""")

In [12]:
con.execute("""
create table if not exists dim_produtos (
            id_produto bigint,
            nm_produto text,
            vl_produto FLOAT
            )
""")

In [18]:
df_dim = con.execute(""" select * from dim_produtos """).fetchdf()
df_dim.head()

   id_produto nm_produto  vl_produto
0       10002    MARTELO      1500.0
1       10001   PARAFUSO       100.0
2       10004      SERRA       200.0
3       10003      PREGO        60.0

In [15]:
con.execute("""
    INSERT INTO dim_produtos SELECT * FROM df2
""")

In [ ]:
con.close()